#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/



task servo()
{

	setServo(servoMotor, 127);
	wait(2);
	setServo(servoMotor, 0);
	wait(2);
	setServo(servoMotor, -127);
	wait(2);
}

task main()
{                                     //Program begins, insert code within curly braces
	//StartTask(servo);
	setServo(servoMotor, 127);
	wait(2);
	setServo(servoMotor, 0);
	wait(2);
	setServo(servoMotor, -127);
	wait(2);
}
