#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	int motorCount;
	motorCount = 0;
	while (motorCount < 3)
	{
		startMotor(rightMotor, 95);
		wait(2);
		stopMotor(rightMotor);
		wait(2);
		motorCount++;								//increment motorCount by 1, same as motorCount += 1 or motorCount = motorCount + 1
	}
}
