#pragma config(Sensor, in3,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patka
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

int g_biggest;
task main()
{                                     //Program begins, insert code within curly braces
	while (true)
	{
		g_biggest = 0;
		while (SensorValue(bumpSwitch) == 0)
		{
			int c_sens_val = SensorValue(potentiometer);	//get current sensor value
			if (c_sens_val > g_biggest)
			{
				g_biggest = c_sens_val;
			}
		}
	}
}
