#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

void LEDControl();	//this is a function declaration

task main()
{                                     //Program begins, insert code within curly braces
	while (true)
	{
		LEDControl();		//function call
	}
}

void LEDControl()		//function definition
{
	if (SensorValue(bumpSwitch) == 1)
	{
		turnLEDOn(green);
	}
	else
	{
		turnLEDOff(green);
	}
}
