#pragma config(Motor,  port2,           leftMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
	//A
	startMotor(rightMotor, 127/2);
	wait(5);
	stopMotor(rightMotor);

	//B
	startMotor(leftMotor, -(127*3)/4);
	wait(2.5);
	stopMotor(leftMotor);

	//C
	startMotor(leftMotor, 127);
	startMotor(rightMotor, 127);
	wait(7.25);
	stopMotor(leftMotor);
	stopMotor(rightMotor);


}
