#pragma config(Motor,  port2,            ,             tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port5,           leftMotor,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces
		startMotor(rightMotor, 127/2);		//Starts right motor at half speed
		startMotor(leftMotor, 127);				//Starts left motor at full speed
		wait(5);
		stopMotor(rightMotor);						//Stops right motor
		stopMotor(leftMotor);							//Stops left motor

		startMotor(rightMotor, -(127/2));	//Reverse right motor
		startMotor(leftMotor, -(127));		//Reverse left motor
		wait(10);
		stopMotor(rightMotor);						//Stops right motor
		stopMotor(leftMotor);							//Stops left motor
}
