#pragma config(Sensor, dgtl12, GreenLED,       sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members: Patrick Kubiak
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task CLED()
{
	//Custom LED controls
	turnLEDOff(GreenLED);
	wait(1);
	turnLEDOn(GreenLED);
	wait(1);
	turnLEDOff(GreenLED);
	wait(1);
	turnLEDOn(GreenLED);
	wait(1);
	turnLEDOff(GreenLED);
}

task main()
{                                     //Program begins, insert code within curly braces
	StartTask(CLED);		//Call custom LED controls function
}
